#!/bin/sh

#
# Run the hook command.
# Note: this will be replaced by the real command during copy.
#

# Fetch the GIT diff and format it as command input:
DIFF=$(git -c diff.mnemonicprefix=false -c diff.noprefix=false --no-pager diff -r -p -m -M --full-index --no-color --staged | cat)

# Grumphp env vars
export COMMIT_MSG_FILE=/home/wwwroot/.git/COMMIT_EDITMSG
export GRUMPHP_GIT_WORKING_DIR="$(git rev-parse --show-toplevel)"

# Run GrumPHP
(cd "." && printf "%s\n" "${DIFF}" | 'docker compose' 'run' '--rm' 'phpcli' '/home/docker/.composer/vendor/bin/grumphp' 'git:pre-commit' '--skip-success-output')
