global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'php-fpm'
    static_configs:
      - targets: ['nginx:80']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']