grumphp:
  environment:
    ascii:
      failed: failed.txt
      succeeded: success.txt
    variables:
      GRUMPHP_GIT_REPOSITORY_DIR: "/home/wwwroot/.git"
      GRUMPHP_PROJECT_DIR: "/home/wwwroot/app"
      GRUMPHP_COMPOSER_DIR: "/home/docker/.composer"
      GRUMPHP_BIN_DIR: "/home/docker/.composer/vendor/bin"
  git_hook_variables:
    EXEC_GRUMPHP_COMMAND: ['docker compose', 'run', '--rm', 'phpcli']
    ENV:
      COMMIT_MSG_FILE: '/home/wwwroot/.git/COMMIT_EDITMSG'
  parallel:
    enabled: true
    max_workers: 32
  fixer:
    enabled: true
    fix_by_default: true
  tasks:
    git_commit_message:
      allow_empty_message: false
      enforce_single_lined_subject: true
      type_scope_conventions: [ ]
      max_body_width: 400
      max_subject_width: 100
#      matchers:
#        Must contain JIRA issue number: /^(JIRA-([0-9]*)|NO-JIRA)/

    phpstan:
      configuration: '/home/wwwroot/app/phpstan.neon'

    phpcsfixer:
      config: '/home/wwwroot/app/.php-cs-fixer.dist.php'

    rector:
      config: '/home/wwwroot/app/rector.php'

    jsonlint:
      detect_key_conflicts: true

    yamllint: ~

    twigcs:
      path: '/home/wwwroot/app/templates'
      severity: 'warning'
      display: 'all'
      ruleset: 'FriendsOfTwig\Twigcs\Ruleset\Official'
      triggered_by: ['twig']
      exclude: []
